AllCops:
  Include:
    - Rakefile

Style/Blocks:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/LineLength:
  Max: 92

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  Enabled: false

Style/RedundantReturn:
  AllowMultipleReturnValues: true
