language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - 2.0.0
before_install:
  - sudo apt-get update
  - sudo apt-get install libgirepository1.0-dev gobject-introspection
