language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - jruby-19mode
  - jruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: jruby-head
install:
  - bundle install --retry=3
before_install:
  - sudo apt-get update
  - sudo apt-get install libgirepository1.0-dev gobject-introspection
