sudo: false
language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
  - ruby-head-clang
  - jruby-19mode
  - jruby-20mode
  - jruby-head
  - jruby-9.0.0.0
  - rbx-2
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: ruby-head-clang
bundler_args: --retry=3
cache: bundler
addons:
  apt:
    packages:
      - libgirepository1.0-dev
      - gobject-introspection
before_install:
  - gem update bundler
